### ISSUE TITLE
Enable bluetooth plugin for LIFF

### ISSUE THREAD

**Issue by kajornsakp** [line/line-things-starter#1]
Hi, I've tried setting up LINE Things with this starter. When it come to register LIFF for trial product, I got response 400 with "Please check existence, channel and BLUETOOTH_LE feature.". But, I can't find any place in developer console to enable bluetooth for the LIFF. So, I wonder how to register this properly?. Also, when open LIFF inside LINE app. It shows that bluetooth plugin is not permitted.

Is it available yet? or did I miss something during setup step? Thanks

p.s. This project is super cool ⭐️⭐️

**Comment by cosmic-cowboy** [comment]
You need to add "BLE" feature like this.
https://developers.line.biz/ja/docs/line-things/regist-liff-app/

You can update your LIFF to add "BLE" feature using "Update LIFF app"
https://developers.line.biz/en/reference/liff/#update-liff-app

**Comment by kajornsakp** [comment]
Oh, I added it from console. That's why I didn't see feature flags 😂

Thanks a lot 🙏 

Also, each time that I updated in developer console. The flag will be removed. Is this a normal behavior?

**Comment by cosmic-cowboy** [comment]
Sorry for inconvenience.
Now we release only Server API to add and update "BLE" feature.
https://developers.line.biz/en/reference/liff/#add-liff-app
but We have a plan to add feature flag on developer console.

**Comment by kajornsakp** [comment]
Ok. Thanks a lot.
