### ISSUE TITLE
Could this support Generic Sensor API?

### ISSUE THREAD

**Issue by scc-tw** [line/line-things-starter#31]
Could liff support support Generic Sensor API?
Just like chrome about this page
https://intel.github.io/generic-sensor-demos/

thanks!

**Comment by hktechn0** [comment]
It depends on user's mobile environment.

I'm not sure about Generic Sensor API.
However, LIFF will be running on webview inside LINE app.
You can use all APIs which is supported on user's webview environment.
https://developers.line.biz/en/docs/liff/overview/
